site_name: Technical Notes


theme:
  name: material
  features:
    - navigation.instant
    - navigation.tabs

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - admonition
  - pymdownx.superfences
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde


extra_javascript:
  - javascripts/config.js
  - https://polyfill.io/v3/polyfill.min.js?features=es6
  - https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js

